config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [ @list, @bookmark] do |f| %>
    raise
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit "Add movie to the list", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<!-- BANNER -->

<div class= "banner-background">
  <div class= "banner-title">

    <h1> Welcome to <br> the Watch List! </h1>
    <p> Create unlimited lists with your favorite movies of all time </p>

    <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Create a list!
    </button>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">What's the name of your movie list?</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <%= simple_form_for [@list] do |f| %>
                <%= f.input :name %>
                <%= f.input :photo, as: :file %>
                <%= f.submit "Create list", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
  <div class= "banner-image">
    <%= image_tag "clapperboard.png", alt: "movie clapperboard", width: 250 %>
  </div>
  <div class="custom-shape-divider-bottom-1650582608">
      <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
          <path d="M985.66,92.83C906.67,72,823.78,31,743.84,14.19c-82.26-17.34-168.06-16.33-250.45.39-57.84,11.73-114,31.07-172,41.86A600.21,600.21,0,0,1,0,27.35V120H1200V95.8C1132.19,118.92,1055.71,111.31,985.66,92.83Z" class="shape-fill"></path>
      </svg>
  </div>
</div>


<!-- LIST CARDS -->

<div class="cards-container">

<% @lists.each do |list| %>
    <%= link_to list_path(list) do %>
      <div class="card-wrapper-list">
           <%= cl_image_tag list.photo.key, height: 300, width: 350, crop: :fill %>
        <div class= "card-info">
          <h2> <%= list.name %>  </h2>
        </div>
      </div>
    <% end %>
  <% end %>


</div>

app/views/lists/new.html.erb
 <%= simple_form_for [@list] do |f| %>
            <%= f.input :name %>
            <%= f.submit "Create list", class: "btn btn-primary" %>
         <% end %>

app/views/lists/show.html.erb
<!-- NAVBAR -->

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
       <%= image_tag "clapperboard.png", width: 50 %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
              <%= link_to "My lists", lists_path %>
          </li>
      </ul>
    </div>
  </div>
</div>


    <%# <%= link_to "Add a movie", new_list_bookmark_path(@list) %>



<!-- BANNER -->
<div class="banner-list" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.7)), url('https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2056&q=80')">
  <div class="banner-list-container">
    <h1> <%= @list.name %> </h1>
  </div>
</div>

<!-- Add a movie form -->
<%= simple_form_for [ @list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Add movie to the list", class: "btn-form" %>
<% end %>


<!-- MOVIE CARD -->

<div class="cards-container">

<% @list.movies.each do |movie| %>
    <div class="card-wrapper-list">
      <%= image_tag movie.poster_url, alt: "movie background", width: 350, height: 380 %>
      <div class= "card-info">
        <h2> <%= movie.title %>  </h2>
        <p> <%= movie.overview %> </p>
      </div>
     </div>
  <% end %>

</div>